apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  name: productcatalog
  labels:
    oda.tmforum.org/componentName: productcatalog
spec:
  type: ocs
  selector:
    matchLabels:
     oda.tmforum.org/componentName: productcatalog
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment  
  version: "0.0.1"
  description: "Simple Product Catalog ODA-Component from Open-API reference implementation." 
  maintainers:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com
  owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com     
  coreFunction:
    exposedAPIs: 
    - name: productcatalogmanagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      implementation: productcatalog
      path: /tmf-api/productCatalogManagement/v4
      developerUI: /tmf-api/productCatalogManagement/v4/docs
      port: 8080
    dependantAPIs: []
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: []
  security:
    securitySchemes: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  labels:
    oda.tmforum.org/componentName: productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
      - name: productcatalog
        image: lesterthomas/productcatalog:latest
        ports:
        - name: productcatalog
          containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    oda.tmforum.org/componentName: productcatalog
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
        - name: mongodb-pv-storage
          mountPath: "/data/db"
      volumes:
      - name: mongodb-pv-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pv-claim
  labels:
    oda.tmforum.org/componentName: productcatalog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    oda.tmforum.org/componentName: productcatalog
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: mongodb
    name: mongodb
  type: NodePort
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  labels:
    app: productcatalog
    oda.tmforum.org/componentName: productcatalog
spec:
  ports:
  - port: 8080
    targetPort: productcatalog
    name: productcatalog
  type: NodePort
  selector:
    app: productcatalog                        