apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prodcat-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prodcat
spec:
  hosts:
  - "*"
  gateways:
  - prodcat-gateway
  http:
  - match:
    - uri:
        prefix: /r1-productcatalog/tmf-api/productCatalogManagement/v4
    route:
    - destination:
        host: r1-prodcatapi
        port:
          number: 8080