apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
spec:
  hosts:
  - "*"
  gateways:
  - prodcat-gateway
  http:
  - match:
    - uri:
        prefix: /{{.Release.Name}}-productcatalog/tmf-api/productCatalogManagement/v4   
    route:
    - destination:
        host: {{.Release.Name}}-prodcatapi
        port:
          number: 8080
  - match:
    - uri:
        prefix: /{{.Release.Name}}-productcatalog/tmf-api/partyRoleManagement/v4   
    route:
    - destination:
        host: {{.Release.Name}}-partyroleapi
        port:
          number: 8080          
